version: '3'

services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gofermart
    ports:
      - "5433:5432"
    volumes:
      - db_pgsql_data:/var/lib/postgresql/data

volumes:
  db_pgsql_data: